
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftSTARSLASHrightUMINUSID STAR AND NUM LPAREN RPAREN COMMA LCURL RCURL SEMICOLON EQUALS INT VOID MAIN PLUS MINUS SLASH prog : VOID MAIN LPAREN RPAREN LCURL body RCURL\n\t\t\t | VOID MAIN LPAREN RPAREN LCURL RCURL\n\t body : stmt body\n\t\t\t | stmt\n\t stmt : decl SEMICOLON \n\t\t\t | assgn_list SEMICOLON\n\t assgn_list : assgn_list COMMA assgn \n\t\t\t  | assgn \n\t assgn : ptr_assgn\n\t \t\t  | num_assgn\n\t decl : INT decl_list\n\t decl_list : decl_list COMMA ID\n\t\t\t\t | decl_list COMMA ptr\n\t\t\t\t | ID\n\t\t\t\t | ptr\n\t ptr_assgn : ptr EQUALS ptr_expr  num_assgn : ID EQUALS addr\n\t\t\t\t  | ID EQUALS ID\n\t\tptr_expr : ptr_expr PLUS ptr_factor \n\t\t\t\t | ptr_expr MINUS ptr_factor\n\t\t\t\t | ptr_factor\n\t\n\t\tptr_factor :  ptr_factor STAR ptr_term\n\t\t\t\t \t| ptr_factor SLASH ptr_term\n\t\t\t\t \t| ptr_term\n\t ptr_term :  MINUS ptr_term  \t\t%prec UMINUS\n\t\t\t\t  | ptr_expr_base\n\t ptr_expr_base : ID\n\t\t\t\t| NUM\n\t\t\t\t| ptr\n\t\t\t\t| addr\n\t  ptr : STAR ptr \n\t\t\t | STAR ID\n\t\t\t | STAR addr\n\t addr : AND ID\n\t\t\t | AND ptr\n\t'
    
_lr_action_items = {'STAR':([6,7,14,15,23,24,25,26,27,28,29,31,33,37,38,39,40,41,42,43,45,46,47,50,51,52,53,54,55,56,57,58,],[14,14,14,14,-6,14,14,14,-32,-31,-33,-5,14,-24,50,-29,-28,-27,-26,14,-30,-34,-35,14,14,-25,14,14,-22,-23,50,50,]),'AND':([14,22,25,43,50,51,53,54,],[26,26,26,26,26,26,26,26,]),'LCURL':([5,],[6,]),'VOID':([0,],[1,]),'RCURL':([6,15,17,23,30,31,],[12,-4,32,-6,-3,-5,]),'EQUALS':([10,13,27,28,29,46,47,],[22,25,-32,-31,-33,-34,-35,]),'COMMA':([8,9,11,18,19,20,21,27,28,29,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,52,55,56,57,58,],[-8,-9,24,-10,-14,33,-15,-32,-31,-33,-18,-17,-7,-24,-21,-29,-28,-27,-26,-16,-30,-34,-35,-12,-13,-25,-22,-23,-20,-19,]),'MAIN':([1,],[3,]),'NUM':([25,43,50,51,53,54,],[40,40,40,40,40,40,]),'ID':([6,7,14,15,22,23,24,25,26,31,33,43,50,51,53,54,],[10,19,27,10,34,-6,10,41,46,-5,48,41,41,41,41,41,]),'MINUS':([25,27,28,29,37,38,39,40,41,42,43,44,45,46,47,50,51,52,53,54,55,56,57,58,],[43,-32,-31,-33,-24,-21,-29,-28,-27,-26,43,53,-30,-34,-35,43,43,-25,43,43,-22,-23,-20,-19,]),'LPAREN':([3,],[4,]),'$end':([2,12,32,],[0,-2,-1,]),'RPAREN':([4,],[5,]),'SLASH':([27,28,29,37,38,39,40,41,42,45,46,47,52,55,56,57,58,],[-32,-31,-33,-24,51,-29,-28,-27,-26,-30,-34,-35,-25,-22,-23,51,51,]),'SEMICOLON':([8,9,11,16,18,19,20,21,27,28,29,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,52,55,56,57,58,],[-8,-9,23,31,-10,-14,-11,-15,-32,-31,-33,-18,-17,-7,-24,-21,-29,-28,-27,-26,-16,-30,-34,-35,-12,-13,-25,-22,-23,-20,-19,]),'PLUS':([27,28,29,37,38,39,40,41,42,44,45,46,47,52,55,56,57,58,],[-32,-31,-33,-24,-21,-29,-28,-27,-26,54,-30,-34,-35,-25,-22,-23,-20,-19,]),'INT':([6,15,23,31,],[7,7,-6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assgn':([6,15,24,],[8,8,36,]),'ptr_term':([25,43,50,51,53,54,],[37,52,55,56,37,37,]),'stmt':([6,15,],[15,15,]),'decl':([6,15,],[16,16,]),'ptr_factor':([25,53,54,],[38,57,58,]),'ptr_expr':([25,],[44,]),'decl_list':([7,],[20,]),'body':([6,15,],[17,30,]),'num_assgn':([6,15,24,],[18,18,18,]),'ptr_assgn':([6,15,24,],[9,9,9,]),'assgn_list':([6,15,],[11,11,]),'ptr_expr_base':([25,43,50,51,53,54,],[42,42,42,42,42,42,]),'prog':([0,],[2,]),'ptr':([6,7,14,15,24,25,26,33,43,50,51,53,54,],[13,21,28,13,13,39,47,49,39,39,39,39,39,]),'addr':([14,22,25,43,50,51,53,54,],[29,35,45,45,45,45,45,45,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> VOID MAIN LPAREN RPAREN LCURL body RCURL','prog',7,'p_def_prog','150050061_17V051001.py',118),
  ('prog -> VOID MAIN LPAREN RPAREN LCURL RCURL','prog',6,'p_def_prog','150050061_17V051001.py',119),
  ('body -> stmt body','body',2,'p_def_body','150050061_17V051001.py',129),
  ('body -> stmt','body',1,'p_def_body','150050061_17V051001.py',130),
  ('stmt -> decl SEMICOLON','stmt',2,'p_def_stmt','150050061_17V051001.py',137),
  ('stmt -> assgn_list SEMICOLON','stmt',2,'p_def_stmt','150050061_17V051001.py',138),
  ('assgn_list -> assgn_list COMMA assgn','assgn_list',3,'p_def_assgn_list','150050061_17V051001.py',145),
  ('assgn_list -> assgn','assgn_list',1,'p_def_assgn_list','150050061_17V051001.py',146),
  ('assgn -> ptr_assgn','assgn',1,'p_def_assgn','150050061_17V051001.py',153),
  ('assgn -> num_assgn','assgn',1,'p_def_assgn','150050061_17V051001.py',154),
  ('decl -> INT decl_list','decl',2,'p_def_decl','150050061_17V051001.py',161),
  ('decl_list -> decl_list COMMA ID','decl_list',3,'p_def_decl_list','150050061_17V051001.py',168),
  ('decl_list -> decl_list COMMA ptr','decl_list',3,'p_def_decl_list','150050061_17V051001.py',169),
  ('decl_list -> ID','decl_list',1,'p_def_decl_list','150050061_17V051001.py',170),
  ('decl_list -> ptr','decl_list',1,'p_def_decl_list','150050061_17V051001.py',171),
  ('ptr_assgn -> ptr EQUALS ptr_expr','ptr_assgn',3,'p_def_ptr_assgn','150050061_17V051001.py',186),
  ('num_assgn -> ID EQUALS addr','num_assgn',3,'p_def_num_assgn','150050061_17V051001.py',198),
  ('num_assgn -> ID EQUALS ID','num_assgn',3,'p_def_num_assgn','150050061_17V051001.py',199),
  ('ptr_expr -> ptr_expr PLUS ptr_factor','ptr_expr',3,'p_def_ptr_expr','150050061_17V051001.py',214),
  ('ptr_expr -> ptr_expr MINUS ptr_factor','ptr_expr',3,'p_def_ptr_expr','150050061_17V051001.py',215),
  ('ptr_expr -> ptr_factor','ptr_expr',1,'p_def_ptr_expr','150050061_17V051001.py',216),
  ('ptr_factor -> ptr_factor STAR ptr_term','ptr_factor',3,'p_def_ptr_factor','150050061_17V051001.py',233),
  ('ptr_factor -> ptr_factor SLASH ptr_term','ptr_factor',3,'p_def_ptr_factor','150050061_17V051001.py',234),
  ('ptr_factor -> ptr_term','ptr_factor',1,'p_def_ptr_factor','150050061_17V051001.py',235),
  ('ptr_term -> MINUS ptr_term','ptr_term',2,'p_def_ptr_term','150050061_17V051001.py',251),
  ('ptr_term -> ptr_expr_base','ptr_term',1,'p_def_ptr_term','150050061_17V051001.py',252),
  ('ptr_expr_base -> ID','ptr_expr_base',1,'p_def_ptr_expr_base','150050061_17V051001.py',264),
  ('ptr_expr_base -> NUM','ptr_expr_base',1,'p_def_ptr_expr_base','150050061_17V051001.py',265),
  ('ptr_expr_base -> ptr','ptr_expr_base',1,'p_def_ptr_expr_base','150050061_17V051001.py',266),
  ('ptr_expr_base -> addr','ptr_expr_base',1,'p_def_ptr_expr_base','150050061_17V051001.py',267),
  ('ptr -> STAR ptr','ptr',2,'p_def_ptr','150050061_17V051001.py',290),
  ('ptr -> STAR ID','ptr',2,'p_def_ptr','150050061_17V051001.py',291),
  ('ptr -> STAR addr','ptr',2,'p_def_ptr','150050061_17V051001.py',292),
  ('addr -> AND ID','addr',2,'p_def_addr','150050061_17V051001.py',302),
  ('addr -> AND ptr','addr',2,'p_def_addr','150050061_17V051001.py',303),
]
